### ISSUE TITLE
第三手棋程序会抛异常

### ISSUE THREAD

**Issue by changjiuxiong** [chncwang/FoolGo#7]
启动项目foolgo，玩家白棋下第三手棋后程序会抛异常。日志：
Assertion failed: node_record.GetVisitedTime() > 0, file e:\project\foolgo\src\player/uct_player.h, line 62

查看源码：
float Ucb(const NodeRecord &node_record, int visited_count_sum) {
  assert(node_record.GetVisitedTime() > 0);
  return node_record.GetAverageProfit()
      + sqrt(2 * log(visited_count_sum) / node_record.GetVisitedTime());
}
发现白棋下第三手棋后模拟过程会出现Ucb节点访问次数为0，导致除0异常

**Comment by chncwang** [comment]
Hmm, I have never met such an error. As far as I remember, the program doesn't check if the input move is legal or not. Are you sure your input move location is correct?

**Comment by changjiuxiong** [comment]
> Hmm, I have never met such an error. As far as I remember, the program doesn't check if the input move is legal or not. Are you sure your input move location is correct?

我确定我的输入是合法的坐标。是不是因为我用的windows平台编译的？我用的vs2017
![095555](https://github.com/chncwang/FoolGo/assets/31230281/5349cfac-70a7-41a5-a8aa-f9fbe82c0d38)

**Comment by chncwang** [comment]
Sorry, I just built this program on Ubuntu and don't see this error. Maybe it has bugs on Windows, which I have never tried to build it on. In addition, it should also work well on Mac OS.
Please feel free to pull requests if you are interested in fixing it.
